[package]
name = "fasta_parser"   # Replace with your project name
version = "0.1.0"
edition = "2021"

[dependencies]
needletail = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

